// ⚠️ AUTO-GENERATED by @betttercms/codegen — DO NOT EDIT.
// Live Preview bindings for BetterCMS. Spread these onto elements that render CMS fields.
// In production builds (no BCMS_ANNOTATE env var), these are empty objects — zero runtime cost.
// In preview builds with BCMS_ANNOTATE, they emit data-bcms-* attributes for Live Preview.

const ANNOTATE = typeof process !== "undefined" && process.env.BCMS_ANNOTATE;

function b(fields: string[], index?: number): Record<string, string> {
  if (!ANNOTATE) return {};
  const path = index !== undefined ? `${fields.join(".")}.${index}` : fields.join(".");
  return { "data-bcms-field": path };
}

export const bcms = {
  experience: {
    roles: {
      $: (i: number) => b(["experience", "roles"], i),
      role: (i: number) => b(["experience", "roles", "role"], i),
      company: (i: number) => b(["experience", "roles", "company"], i),
      start: (i: number) => b(["experience", "roles", "start"], i),
      end: (i: number) => b(["experience", "roles", "end"], i),
      scope: (i: number) => b(["experience", "roles", "scope"], i),
    },
    certifications: {
      $: (i: number) => b(["experience", "certifications"], i),
      name: (i: number) => b(["experience", "certifications", "name"], i),
      issuer: (i: number) => b(["experience", "certifications", "issuer"], i),
      year: (i: number) => b(["experience", "certifications", "year"], i),
      url: (i: number) => b(["experience", "certifications", "url"], i),
    },
  },
  home: {
    identity: {
      name: b(["home", "identity", "name"]),
      role: b(["home", "identity", "role"]),
      tagline: b(["home", "identity", "tagline"]),
      location: b(["home", "identity", "location"]),
      timezone: b(["home", "identity", "timezone"]),
      status: b(["home", "identity", "status"]),
    },
    about: {
      paragraph_1: b(["home", "about", "paragraph_1"]),
      paragraph_2: b(["home", "about", "paragraph_2"]),
      paragraph_3: b(["home", "about", "paragraph_3"]),
    },
    contact: {
      email: b(["home", "contact", "email"]),
      github: b(["home", "contact", "github"]),
      linkedin: b(["home", "contact", "linkedin"]),
      x: b(["home", "contact", "x"]),
      website: b(["home", "contact", "website"]),
    },
  },
  projects: {
    projects: {
      $: (i: number) => b(["projects", "projects"], i),
      title: (i: number) => b(["projects", "projects", "title"], i),
      year: (i: number) => b(["projects", "projects", "year"], i),
      place: (i: number) => b(["projects", "projects", "place"], i),
      description: (i: number) => b(["projects", "projects", "description"], i),
      lat: (i: number) => b(["projects", "projects", "lat"], i),
      lng: (i: number) => b(["projects", "projects", "lng"], i),
      href: (i: number) => b(["projects", "projects", "href"], i),
      repo: (i: number) => b(["projects", "projects", "repo"], i),
      stack: {
        value: (i: number, j: number) => b(["projects", "projects", "stack"], j),
      },
    },
  },
  skills: {
    categories: {
      $: (i: number) => b(["skills", "categories"], i),
      category_name: (i: number) => b(["skills", "categories", "category_name"], i),
      skills: {
        value: (i: number, j: number) => b(["skills", "categories", "skills"], j),
      },
    },
    heading: {
      title: b(["skills", "heading", "title"]),
      subtitle: b(["skills", "heading", "subtitle"]),
    },
  },
};