// ⚠️  AUTO-GENERATED by @betttercms/codegen v0.2.0 — DO NOT EDIT.
// Regenerate with: npx @betttercms/codegen
// Source of truth: your BetterCMS content models (the same schema the dashboard
// builder and the MCP tools write). Re-run codegen after any schema change.

/**
 * Rich-text field value returned by the Delivery API.
 *
 * - `format`/`value`: the portable, editor-agnostic payload (Lexical EditorState) —
 *   render it with your editor's serializer for full fidelity.
 * - `html`: server-rendered, sanitized HTML (computed render-on-write). Present on
 *   Delivery reads; the simplest path for non-React consumers — safe to inject directly
 *   (e.g. `dangerouslySetInnerHTML`). Optional: legacy/un-normalized values may omit it.
 *
 * The `{ format, value }` contract is unchanged; `html` is additive.
 */
export type RichText = {
  readonly format: string;
  readonly value: unknown;
  readonly html?: string;
};

/**
 * Image / media field value as stored and returned verbatim by the Delivery API
 * (server-normalized on write to the canonical shape). `url` is always present; an
 * unresolved/external value may carry only `url`. `altText` is the accessibility text
 * for `<img alt>`.
 */
export interface BetterCMSImage {
  readonly id?: string;
  readonly url: string;
  readonly name?: string;
  readonly altText?: string | null;
  readonly width?: number;
  readonly height?: number;
}

/**
 * Delivery envelope around a model's typed `data`. `getEntry`/`listEntries` in the
 * Next adapter return this shape, with `fields` typed by the model.
 */
export interface BetterCMSEntry<TFields> {
  readonly slug: string;
  readonly status: "draft" | "published";
  readonly fields: TFields;
  readonly updatedAt: string;
}

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

/** Home page — singleton */
export interface HomeFields {
  readonly name: string;
  readonly role: string;
  readonly tagline: string;
  readonly location: string;
  readonly timezone: string;
  readonly status: string;
  readonly email: string;
  readonly github: string;
  readonly linkedin: string;
  readonly x: string;
  readonly website: string;
  readonly about: {
    readonly paragraph_1: string;
    readonly paragraph_2: string;
    readonly paragraph_3: string;
  };
  readonly contact: {
    readonly email_display: string;
    readonly github_url: string;
    readonly linkedin_url: string;
    readonly x_url: string;
    readonly website_url: string;
  };
}

/** Projects — dynamic collection */
export interface ProjectsFields {
  readonly title: string;
  readonly year: string;
  readonly place: string;
  readonly description: RichText;
  readonly stack: readonly string[];
  readonly href: string;
  readonly repo: string;
  readonly lat: number;
  readonly lng: number;
}

/** Experience page — singleton */
export interface ExperienceFields {
  readonly roles: readonly {
    readonly role: string;
    readonly company: string;
    readonly start: string;
    readonly end: string;
    readonly scope: string;
  }[];
}

/** Skills page — singleton */
export interface SkillsFields {
  readonly categories: readonly {
    readonly category_name: string;
    readonly skills: readonly string[];
  }[];
}

// ---------------------------------------------------------------------------
// Schema registry
// ---------------------------------------------------------------------------

/**
 * Registry mapping each model slug to its typed fields. The Next adapter uses this to
 * type `getEntry("blog", ...)` by slug — autocomplete and exhaustiveness for free.
 */
export interface BetterCMSSchema {
  home: HomeFields;
  projects: ProjectsFields;
  experience: ExperienceFields;
  skills: SkillsFields;
}

/** Union of all model slugs. */
export type BetterCMSModelSlug = keyof BetterCMSSchema;