// ⚠️  AUTO-GENERATED by @betttercms/codegen v0.3.0 — DO NOT EDIT.
// Regenerate with: npx @betttercms/codegen
// Source of truth: your BetterCMS pages (the same schema the dashboard
// builder and the MCP tools write). Re-run codegen after any schema change.

/**
 * Rich-text field value returned by the Delivery API.
 *
 * - `format`/`value`: the portable, editor-agnostic payload (Lexical EditorState) —
 *   render it with your editor's serializer for full fidelity.
 * - `html`: server-rendered, sanitized HTML (computed render-on-write). Present on
 *   Delivery reads; the simplest path for non-React consumers — safe to inject directly
 *   (e.g. `dangerouslySetInnerHTML`). Optional: legacy/un-normalized values may omit it.
 *
 * The `{ format, value }` contract is unchanged; `html` is additive.
 */
export type RichText = {
  readonly format: string;
  readonly value: unknown;
  readonly html?: string;
};

/**
 * Image / media field value as stored and returned verbatim by the Delivery API
 * (server-normalized on write to the canonical shape). `url` is always present; an
 * unresolved/external value may carry only `url`. `altText` is the accessibility text
 * for `<img alt>`.
 */
export interface BetterCMSImage {
  readonly id?: string;
  readonly url: string;
  readonly name?: string;
  readonly altText?: string | null;
  readonly width?: number;
  readonly height?: number;
}

/**
 * Delivery envelope around a model's typed `data`. `getEntry`/`listEntries` in the
 * Next adapter return this shape, with `fields` typed by the model.
 */
export interface BetterCMSEntry<TFields> {
  readonly slug: string;
  readonly status: "draft" | "published";
  readonly fields: TFields;
  readonly updatedAt: string;
}

/**
 * Experience
 * Page slug: `experience`
 */
export interface ExperienceFields {
  /** Roles */
  readonly roles?: {
    readonly repeatable?: Array<{
      /** Role */
      readonly role: string;
      /** Company */
      readonly company: string;
      /** Start */
      readonly start?: string;
      /** End */
      readonly end?: string;
      /** Scope */
      readonly scope?: string;
    }>;
  };
  /** Certifications */
  readonly certifications?: {
    readonly repeatable?: Array<{
      /** Name */
      readonly name: string;
      /** Issuer */
      readonly issuer?: string;
      /** Year */
      readonly year?: string;
      /** URL */
      readonly url?: string;
    }>;
  };
}

/**
 * Home
 * Page slug: `home`
 */
export interface HomeFields {
  /** Identity */
  readonly identity?: {
    readonly nonRepeatable?: {
      /** Name */
      readonly name: string;
      /** Role */
      readonly role: string;
      /** Tagline */
      readonly tagline?: string;
      /** Location */
      readonly location?: string;
      /** Timezone */
      readonly timezone?: string;
      /** Status */
      readonly status?: string;
    };
  };
  /** About */
  readonly about?: {
    readonly nonRepeatable?: {
      /** Paragraph 1 */
      readonly paragraph_1?: string;
      /** Paragraph 2 */
      readonly paragraph_2?: string;
      /** Paragraph 3 */
      readonly paragraph_3?: string;
    };
  };
  /** Contact */
  readonly contact?: {
    readonly nonRepeatable?: {
      /** Email */
      readonly email?: string;
      /** GitHub URL */
      readonly github?: string;
      /** LinkedIn URL */
      readonly linkedin?: string;
      /** X/Twitter URL */
      readonly x?: string;
      /** Website URL */
      readonly website?: string;
    };
  };
}

/**
 * Projects
 * Page slug: `projects`
 */
export interface ProjectsFields {
  /** Projects */
  readonly projects?: {
    readonly repeatable?: Array<{
      /** Title */
      readonly title: string;
      /** Year */
      readonly year?: string;
      /** Place */
      readonly place?: string;
      /** Description */
      readonly description?: RichText;
      /** Latitude */
      readonly lat?: number;
      /** Longitude */
      readonly lng?: number;
      /** Live URL */
      readonly href?: string;
      /** Repo URL */
      readonly repo?: string;
      /** Stack */
      readonly stack?: string[];
    }>;
  };
}

/**
 * Skills
 * Page slug: `skills`
 */
export interface SkillsFields {
  /** Categories */
  readonly categories?: {
    readonly repeatable?: Array<{
      /** Category Name */
      readonly category_name: string;
      /** Skills */
      readonly skills?: string[];
    }>;
  };
  /** Heading */
  readonly heading?: {
    readonly nonRepeatable?: {
      /** Title */
      readonly title: string;
      /** Subtitle */
      readonly subtitle?: string;
    };
  };
}

/**
 * Registry mapping each page/model slug to its typed fields. The Next adapter uses this to
 * type `getEntry("home", ...)` by slug — autocomplete and exhaustiveness for free.
 */
export interface BetterCMSSchema {
  readonly "experience": ExperienceFields;
  readonly "home": HomeFields;
  readonly "projects": ProjectsFields;
  readonly "skills": SkillsFields;
}

/** Union of all model slugs. */
export type BetterCMSModelSlug = keyof BetterCMSSchema;